try:
    d=[1,2]
    print(d[5])
except Exception:
    print('error handled')    